// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBroker(arg1, arg2) {
  return window['go']['main']['App']['AddBroker'](arg1, arg2);
}

export function AddBrokerCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBrokerCredential'](arg1, arg2, arg3);
}

export function AlterTopicConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AlterTopicConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearActiveBrokerCredential(arg1, arg2) {
  return window['go']['main']['App']['ClearActiveBrokerCredential'](arg1, arg2);
}

export function CommitSession(arg1) {
  return window['go']['main']['App']['CommitSession'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function CreateTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTopic'](arg1, arg2, arg3);
}

export function DeleteBroker(arg1, arg2) {
  return window['go']['main']['App']['DeleteBroker'](arg1, arg2);
}

export function DeleteBrokerCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBrokerCredential'](arg1, arg2, arg3);
}

export function DeleteConsumerGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteConsumerGroup'](arg1, arg2, arg3);
}

export function DeletePlugin(arg1) {
  return window['go']['main']['App']['DeletePlugin'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTopic'](arg1, arg2, arg3);
}

export function DeleteTopicGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTopicGroup'](arg1, arg2, arg3);
}

export function DescribeConsumerGroupMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['DescribeConsumerGroupMembers'](arg1, arg2, arg3);
}

export function ExportSettings(arg1) {
  return window['go']['main']['App']['ExportSettings'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetClusterInfo(arg1, arg2) {
  return window['go']['main']['App']['GetClusterInfo'](arg1, arg2);
}

export function GetClusterStats(arg1, arg2) {
  return window['go']['main']['App']['GetClusterStats'](arg1, arg2);
}

export function GetConsumerGroupDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConsumerGroupDetail'](arg1, arg2, arg3);
}

export function GetTopicConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopicConfig'](arg1, arg2, arg3);
}

export function GetTopicMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopicMetadata'](arg1, arg2, arg3);
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function InvalidateTopicsCache(arg1) {
  return window['go']['main']['App']['InvalidateTopicsCache'](arg1);
}

export function ListAllConsumerGroups(arg1, arg2) {
  return window['go']['main']['App']['ListAllConsumerGroups'](arg1, arg2);
}

export function ListConsumerGroups(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListConsumerGroups'](arg1, arg2, arg3);
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListTopics(arg1, arg2) {
  return window['go']['main']['App']['ListTopics'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PinTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['PinTopic'](arg1, arg2, arg3);
}

export function ProduceMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProduceMessage'](arg1, arg2, arg3);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ResetConsumerGroup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ResetConsumerGroup'](arg1, arg2, arg3, arg4, arg5);
}

export function SavePlugin(arg1) {
  return window['go']['main']['App']['SavePlugin'](arg1);
}

export function SaveTopicGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTopicGroup'](arg1, arg2, arg3);
}

export function SetBrokerPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBrokerPassword'](arg1, arg2, arg3);
}

export function SetNamedCredentialPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetNamedCredentialPassword'](arg1, arg2, arg3, arg4);
}

export function SetSchemaRegistryPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSchemaRegistryPassword'](arg1, arg2, arg3);
}

export function StartConsumer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartConsumer'](arg1, arg2, arg3, arg4, arg5);
}

export function StartObserver(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartObserver'](arg1, arg2, arg3, arg4);
}

export function StartObserverAtTimestamp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartObserverAtTimestamp'](arg1, arg2, arg3, arg4);
}

export function StartRateWatcher(arg1, arg2) {
  return window['go']['main']['App']['StartRateWatcher'](arg1, arg2);
}

export function StartSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSearch'](arg1, arg2, arg3);
}

export function StopRateWatcher(arg1) {
  return window['go']['main']['App']['StopRateWatcher'](arg1);
}

export function StopSearch(arg1) {
  return window['go']['main']['App']['StopSearch'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function SwitchBrokerCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchBrokerCredential'](arg1, arg2, arg3);
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestBrokerConnection(arg1, arg2) {
  return window['go']['main']['App']['TestBrokerConnection'](arg1, arg2);
}

export function TestConnectionDirect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestConnectionDirect'](arg1, arg2, arg3, arg4);
}

export function UnpinTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnpinTopic'](arg1, arg2, arg3);
}

export function UpdateBroker(arg1, arg2) {
  return window['go']['main']['App']['UpdateBroker'](arg1, arg2);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
