// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';
import {updater} from '../models';
import {broker} from '../models';
import {plugin} from '../models';
import {search} from '../models';

export function AddBroker(arg1:string,arg2:profile.Broker):Promise<profile.Broker>;

export function AddBrokerCredential(arg1:string,arg2:string,arg3:profile.NamedCredential):Promise<profile.NamedCredential>;

export function AlterTopicConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CheckForUpdates():Promise<updater.Release>;

export function ClearActiveBrokerCredential(arg1:string,arg2:string):Promise<void>;

export function CommitSession(arg1:string):Promise<void>;

export function CreateProfile(arg1:string):Promise<profile.Profile>;

export function CreateTopic(arg1:string,arg2:string,arg3:broker.CreateTopicRequest):Promise<void>;

export function DeleteBroker(arg1:string,arg2:string):Promise<void>;

export function DeleteBrokerCredential(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteConsumerGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePlugin(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteTopic(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTopicGroup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DescribeConsumerGroupMembers(arg1:string,arg2:string,arg3:string):Promise<Array<broker.GroupMemberInfo>>;

export function ExportSettings(arg1:boolean):Promise<void>;

export function GetActiveProfile():Promise<profile.Profile>;

export function GetAppVersion():Promise<string>;

export function GetClusterInfo(arg1:string,arg2:string):Promise<broker.ClusterInfo>;

export function GetClusterStats(arg1:string,arg2:string):Promise<broker.ClusterStats>;

export function GetConsumerGroupDetail(arg1:string,arg2:string,arg3:string):Promise<broker.GroupDetail>;

export function GetTopicConfig(arg1:string,arg2:string,arg3:string):Promise<Array<broker.TopicConfigEntry>>;

export function GetTopicMetadata(arg1:string,arg2:string,arg3:string):Promise<broker.TopicMetadata>;

export function ImportSettings():Promise<void>;

export function InvalidateTopicsCache(arg1:string):Promise<void>;

export function ListAllConsumerGroups(arg1:string,arg2:string):Promise<Array<broker.GroupSummary>>;

export function ListConsumerGroups(arg1:string,arg2:string,arg3:string):Promise<Array<broker.GroupLag>>;

export function ListPlugins():Promise<Array<plugin.Plugin>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListTopics(arg1:string,arg2:string):Promise<Array<broker.Topic>>;

export function OpenURL(arg1:string):Promise<void>;

export function PinTopic(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ProduceMessage(arg1:string,arg2:string,arg3:broker.ProduceRequest):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetConsumerGroup(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SavePlugin(arg1:plugin.Plugin):Promise<plugin.Plugin>;

export function SaveTopicGroup(arg1:string,arg2:string,arg3:profile.TopicGroup):Promise<void>;

export function SelectCertificateFile():Promise<string>;

export function SetBrokerPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetNamedCredentialPassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetSchemaRegistryPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartConsumer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StartObserver(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartObserverAtTimestamp(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function StartRateWatcher(arg1:string,arg2:string):Promise<void>;

export function StartSearch(arg1:string,arg2:string,arg3:search.SearchRequest):Promise<string>;

export function StopRateWatcher(arg1:string):Promise<void>;

export function StopSearch(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function SwitchBrokerCredential(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function TestBrokerConnection(arg1:string,arg2:string):Promise<void>;

export function TestConnectionDirect(arg1:Array<string>,arg2:profile.TLSConfig,arg3:profile.SASLConfig,arg4:string):Promise<void>;

export function UnpinTopic(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateBroker(arg1:string,arg2:profile.Broker):Promise<void>;

export function UpdateProfile(arg1:profile.Profile):Promise<void>;
